name: weekly_agg_validation
config_version: 1.0
class_name: SimpleCheckpoint

validations:
  - batch_request:
      datasource_name: nasdaq_athena_datasource
      data_connector_name: default_runtime_data_connector
      data_asset_name: agg_stock_weekly_metrics
      runtime_parameters:
        query: >
          SELECT * FROM nasdaq_airflow_warehouse_dev.agg_stock_weekly_metrics 
          WHERE year = YEAR(CURRENT_DATE) 
            AND week = WEEK(CURRENT_DATE)
      batch_identifiers:
        default_identifier_name: "weekly_agg_{{ execution_date }}"
    
    expectation_suite_name: agg_stock_weekly_metrics_suite

action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
